name: Deploy React to GitHub Pages

on:
  push:
    branches: [ "main" ]  # 保持与你实际分支名一致
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      deployment-url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "22.13.0"
        cache: 'pnpm'

    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8.15.3

    - name: Install dependencies
      run: pnpm install --frozen-lockfile --prod=false

    - name: Build project
      run: pnpm build
      env:
        PUBLIC_URL: "/option-view"

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      id: deployment
      with:
        path: './build'

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: 
      name: github-pages  # 使用GitHub预定义的环境名
      url: ${{ needs.build.outputs.deployment-url }}
    steps:
    - name: Deploy
      uses: actions/deploy-pages@v4